# Generated by Django 3.2 on 2021-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRY_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=64)),
                ('description1', models.CharField(max_length=500)),
                ('description2', models.CharField(max_length=500)),
                ('description3', models.CharField(max_length=500)),
                ('description4', models.CharField(max_length=500)),
                ('description5', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
