# Generated by Django 3.2 on 2021-11-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRY_APP', '0003_remove_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Action', max_length=64),
        ),
        migrations.AddField(
            model_name='game',
            name='system',
            field=models.CharField(default='Multiplatform', max_length=64),
        ),
    ]
