# Generated by Django 3.2 on 2021-11-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRY_APP', '0004_auto_20211127_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pc',
            field=models.URLField(default=111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='playstation',
            field=models.URLField(default=22222222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='xbox',
            field=models.URLField(default=33333333),
            preserve_default=False,
        ),
    ]
