# Generated by Django 3.2 on 2021-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRY_APP', '0009_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(),
        ),
    ]
